### ISSUE TITLE
I got following problem when training NSRR model. 

### ISSUE THREAD

**Issue by JinYangNi** [INTEW/NSRR#2]
E:\Anaconda\lib\site-packages\torch\nn\functional.py:3509: UserWarning: nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.")
Train Epoch: 1 [0/67 (0%)] Loss: 0.908627
Train Epoch: 1 [12/67 (18%)] Loss: 0.491725
Train Epoch: 1 [24/67 (36%)] Loss: 0.551915
Train Epoch: 1 [36/67 (54%)] Loss: 0.453194
Train Epoch: 1 [48/67 (72%)] Loss: 0.465921
Train Epoch: 1 [60/67 (90%)] Loss: 0.326903
Traceback (most recent call last):
  File "G:\Deeplearning\NeuralSupersampling\NSRR-main\train.py", line 74, in <module>
    main(config)
  File "G:\Deeplearning\NeuralSupersampling\NSRR-main\train.py", line 55, in main
    trainer.train()
  File "G:\Deeplearning\NeuralSupersampling\NSRR-main\base\base_trainer.py", line 67, in train
    log.update(result)
TypeError: 'NoneType' object is not iterable

**Comment by Whisper-MMM** [comment]
> E:\Anaconda\lib\site-packages\torch\nn\functional.py:3509: UserWarning: nn.functional.upsample is deprecated. Use nn.functional.interpolate instead. warnings.warn("nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.") Train Epoch: 1 [0/67 (0%)] Loss: 0.908627 Train Epoch: 1 [12/67 (18%)] Loss: 0.491725 Train Epoch: 1 [24/67 (36%)] Loss: 0.551915 Train Epoch: 1 [36/67 (54%)] Loss: 0.453194 Train Epoch: 1 [48/67 (72%)] Loss: 0.465921 Train Epoch: 1 [60/67 (90%)] Loss: 0.326903 Traceback (most recent call last): File "G:\Deeplearning\NeuralSupersampling\NSRR-main\train.py", line 74, in main(config) File "G:\Deeplearning\NeuralSupersampling\NSRR-main\train.py", line 55, in main trainer.train() File "G:\Deeplearning\NeuralSupersampling\NSRR-main\base\base_trainer.py", line 67, in train log.update(result) TypeError: 'NoneType' object is not iterable

It seems that each input is 12 pictures, but the total number of pictures is not a multiple of 12, resulting in an empty input. And the pictures in the data set seem to differ from the actual number of pictures that can be read. I loaded the 192 images one epoch for training, but only 187 were loaded.
